base_repo = "https://github.com/gmarmstrong/remote-dev"
base_dir = "remote-dev"
base_branch = "main"

dotfiles_repo = "https://github.com/gmarmstrong/dotfiles"
dotfiles_dir = "dotfiles"
dotfiles_branch = "bootstrap"
dotfiles_script = "bootstrap.sh"

gcp_project_id = "gmarmstrong"
gce_source_image_family = "ubuntu-2004-lts"
gce_source_image_project_id = "ubuntu-os-cloud"
gce_zone = "us-east1-b"
name = "remote-dev"
ssh_username = "guthrie"