name: Packer

on:
  push:
    paths:
      - "packer/"
      - ".github/workflows/packer.yml"
  pull_request:
    paths:
      - "packer/"
      - ".github/workflows/packer.yml"
  workflow_dispatch:

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Validate Packer template

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: .
          working_directory: packer
