name: tfsec-pr-commenter
on:
  pull_request:
jobs:
  tfsec:
    name: tfsec PR commenter
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Delete cloud-builders-community
        run: rm -rf cloud-builders-community
        # workaround since pr commenter cannot specify terraform/ working directory due to known bug

      - name: tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@v1.2.0
        with:
          github_token: ${{ github.token }}
          tfsec_args: --force-all-dirs
          tfsec_formats: default,sarif
