name: tfsec
on: [push, pull_request, workflow_dispatch]
jobs:
  tfsec:
    name: tfsec sarif report
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: [ terraform/modules/remote-dev, terraform/env/prod, terraform/states ]

    steps:
      - name: Clone repo
        uses: actions/checkout@master

      - name: tfsec sarif
        uses: tfsec/tfsec-sarif-action@main
        with:
          sarif_file: tfsec.sarif         
          working_directory: terraform/

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: tfsec.sarif    
